%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/hp/GitHub/EEG/data/NYU_ECoG_Catalog.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/09/19 17:51:42

%% Initialize variables.
filename = '/Users/hp/GitHub/EEG/data/NYU_ECoG_Catalog.csv';
delimiter = ',';
startRow = 2;

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,5,6,9,10,11,22]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,2,3,5,6,9,10,11,22]);
rawStringColumns = string(raw(:, [4,7,8,12,13,14,15,16,17,18,19,20,21]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [2,3,4,5,6,7,8,9,10,11]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
Catalog_raw = table;
Catalog_raw.Initials = cell2mat(rawNumericColumns(:, 1));
Catalog_raw.PatientID = cell2mat(rawNumericColumns(:, 2));
Catalog_raw.DeviceID = cell2mat(rawNumericColumns(:, 3));
Catalog_raw.Timestamp = rawStringColumns(:, 1);
Catalog_raw.Sessionfolder = cell2mat(rawNumericColumns(:, 4));
Catalog_raw.Filename = cell2mat(rawNumericColumns(:, 5));
Catalog_raw.ECoGtype = categorical(rawStringColumns(:, 2));
Catalog_raw.ECoGtrigger = categorical(rawStringColumns(:, 3));
Catalog_raw.ECoGlength = cell2mat(rawNumericColumns(:, 6));
Catalog_raw.Samplingrate = cell2mat(rawNumericColumns(:, 7));
Catalog_raw.Waveformcount = cell2mat(rawNumericColumns(:, 8));
Catalog_raw.Ch1name = categorical(rawStringColumns(:, 4));
Catalog_raw.Ch2name = categorical(rawStringColumns(:, 5));
Catalog_raw.Ch3name = categorical(rawStringColumns(:, 6));
Catalog_raw.Ch4name = categorical(rawStringColumns(:, 7));
Catalog_raw.Ch1enabled = categorical(rawStringColumns(:, 8));
Catalog_raw.Ch2enabled = categorical(rawStringColumns(:, 9));
Catalog_raw.Ch3enabled = categorical(rawStringColumns(:, 10));
Catalog_raw.Ch4enabled = categorical(rawStringColumns(:, 11));
Catalog_raw.RawUTCTimestamp = rawStringColumns(:, 12);
Catalog_raw.RawLocalTimestamp = rawStringColumns(:, 13);
Catalog_raw.ECoGPretriggerlength = cell2mat(rawNumericColumns(:, 9));

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp rawNumericColumns rawStringColumns R catIdx idx;